# This is a basic workflow to help you get started with Actions

name: Auto Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'o-api.lua'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-docs:
    name: Generate Documentation
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Pull Wiki
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git
          ls -a
          
      # - uses: jannekem/run-python-script-action@v1
      #   name: Generate Documenation
      #   id: script
      #   with:
      #     script: |
      - name: Generate Documenation
        run: |
          python /.github/workflows/autodocs.py
        
      - name: Push API File to Wiki
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './character-select-coop.wiki'
          destination-github-username: 'Squishy6094'
          destination-repository-name: 'character-select-coop.wiki'
          user-email: squishy6094@gmail.com
          target-branch: master
          commit-message: Autogen Docs
